# -*- coding: utf-8 -*-
"""Tarea 2 Programacion I.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TNkMJdAJyCGn61RzYMuYf0W-QCwVMotz

Integrantes del equipo:

Silva Silva Arizbe Itzari

González Hernández Isai
"""

'''
Created on March, 2026
@author: isaighernandez, arizbesilva0-star

'''
class Numero:
    def __init__(self, valor):
        self.valor = valor

    def latex(self):
        return str(self.valor)

    def evaluar(self, variables=None):
        return self.valor

    def __add__(self, otro): return Suma(self, otro)
    def __sub__(self, otro): return Resta(self, otro)
    def __mul__(self, otro): return Producto(self, otro)
    def __pow__(self, otro): return Potencia(self, otro)

class Potencia:
    def __init__(self, base, exponente):
        self.base = Numero(base) if isinstance(base, (int, float)) else base
        self.exp = Numero(exponente) if isinstance(exponente, (int, float)) else exponente

    def __add__(self, otro): return Suma(self, otro)
    def __sub__(self, otro): return Resta(self, otro)
    def __mul__(self, otro): return Producto(self, otro)
    def __rmul__(self, otro): return Producto(otro, self)
    def __pow__(self, otro): return Potencia(self, otro)

    def latex(self):
        return "{"+f"{self.base.latex()}""}^"+f"{self.exp.latex()}"

    def _repr_latex_(self): return f"$${self.latex()}$$"

    def evaluar(self,variables=None):
        evaluar_base= self.base.evaluar(variables)
        evaluar_exp=self.exp.evaluar(variables)
        return evaluar_base**evaluar_exp

class Producto:
    def __init__(self, izq, der):
        self.izq = Numero(izq) if isinstance(izq, (int, float)) else izq
        self.der = Numero(der) if isinstance(der, (int, float)) else der

    def __add__(self, otro): return Suma(self, otro)
    def __sub__(self, otro): return Resta(self, otro)
    def __mul__(self, otro): return Producto(self, otro)
    def __rmul__(self, otro): return Producto(otro, self)
    def __pow__(self, otro): return Potencia(self, otro)

    def latex(self):
        return f"({self.izq.latex()})({self.der.latex()}) "

    def _repr_latex_(self): return f"$${self.latex()}$$"

    def evaluar (self,variables=None):
        evaluar_izq =self.izq.evaluar(variables)
        evaluar_der= self.der.evaluar(variables)
        return evaluar_izq*evaluar_der

class Resta:
    def __init__(self, izq, der):
        self.izq = Numero(izq) if isinstance(izq, (int, float)) else izq
        self.der = Numero(der) if isinstance(der, (int, float)) else der

    def __add__(self, otro): return Suma(self, otro)
    def __sub__(self, otro): return Resta(self, otro)
    def __rsub__(self, otro): return Resta(otro, self)
    def __mul__(self, otro): return Producto(self, otro)
    def __pow__(self, otro): return Potencia(self, otro)


    def latex(self):
        return f"{self.izq.latex()}-{self.der.latex()}"


    def _repr_latex_(self): return f"$${self.latex()}$$"

    def evaluar (self,variables=None):
        evaluar_izq =self.izq.evaluar(variables)
        evaluar_der= self.der.evaluar(variables)
        return evaluar_izq-evaluar_der

class Suma:
    def __init__(self, izq, der):
        self.izq = Numero(izq) if isinstance(izq, (int, float)) else izq
        self.der = Numero(der) if isinstance(der, (int, float)) else der

    def __add__(self, otro): return Suma(self, otro)
    def __sub__(self, otro): return Resta(self, otro)
    def __mul__(self, otro): return Producto(self, otro)
    def __pow__(self, otro): return Potencia(self, otro)

    def latex(self):
        return f"{self.izq.latex()}+{self.der.latex()}"
    def _repr_latex_(self): return f"$${self.latex()}$$"

    def evaluar (self,variables=None):
        evaluar_izq =self.izq.evaluar(variables)
        evaluar_der= self.der.evaluar(variables)
        return evaluar_izq+evaluar_der

class Variable:
    def __init__(self, nombre):
        self.nombre = nombre

    def __add__(self, otro): return Suma(self, otro)
    def __sub__(self, otro): return Resta(self, otro)
    def __mul__(self, otro): return Producto(self, otro)
    def __pow__(self, otro): return Potencia(self, otro)

    def __radd__(self, otro): return Suma(otro, self)
    def __rsub__(self, otro): return Resta(otro, self)
    def __rmul__(self, otro): return Producto(otro, self)


    def evaluar(self,variables= None):
        if variables is not None and self.nombre in variables:
         return variables[self.nombre]
        else:
           return self

    def latex(self):
      if len(self.nombre) > 1:
        return f"\\{self.nombre}"
      return self.nombre

    def _repr_latex_(self):
      return f"$${self.latex()}$$"





   # def latex(self):
    #    return str(self.nombre)

    #def _repr_latex_(self):
     # if len(self.nombre) > 1:
      #return f"$$\\{self.nombre()}$$"
      #else:
       # return f"$${self.latex()}$$"

x = Variable("x")
y = Variable("alpha")

expr = (x + 2) * (y - 5)**2

display(expr)

valores = {"x": 10,"alpha": 8}

resultado = expr.evaluar(valores)
print(resultado)

